version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "desafio_soft_expert"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/data/postgres
      - ./database/dump:/docker-entrypoint-initdb.d
    networks:
      - postgres-db-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./etc/conf/pgadmin/servers.json:/pgadmin4/servers.json:ro
    ports:
      - "5050:80"
    networks:
      - postgres-db-network
    restart: unless-stopped

networks:
  postgres-db-network:
    driver: bridge

volumes:
  postgres-db-volume:
  pgadmin: